# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

collect_youtube_videos:
  description: >
    Search for videos about {topic} in youtube.
    
  expected_output: >
    The 5 videos the more relevant as {videos_list}

make_courses:
  description: >
    1. From {videos_links}, you retrieve the transcripts of the videos, you concatenante all the transcripts and you make one structured  course with all the details from the transcripts. 
    2. You store the course in GCS in a folder named {topic} the name of the file is 'course'.
    
  expected_output: >
    A structured course

generate_quizz:
  description: >
    1. From an course you'll create a multiple-choice test with 5 questions
    2. You store the test in GCS in a folded named {topic} the name of the file is 'test'.

  expected_output: >
    A json with 5 question and the following fields:
    - question: question 
    - answers: possibles answers
    - correct_answer: the right answer